# https://packit.dev/docs/configuration/

specfile_path: image-builder.spec

files_to_sync:
  - image-builder.spec
  - .packit.yaml

copy_upstream_release_description: true

upstream_tag_template: v{version}

srpm_build_deps:
  - make
  - golang

actions:
  # v1 just the default prior to having tags
  get-current-version: bash -c "make show-version"
  post-upstream-clone: bash -c "make patch-spec-in-place"
  create-archive: bash -c "make release_artifacts"

# Handle only releases without a "dot" (e.g. v88.2), since "dot" releases should never be released to Fedora
upstream_tag_include: 'v\d+'

jobs:
  # image-builder is not yet in Fedora, so we don't need to update it there
  # - job: bodhi_update
  #   trigger: commit
  #   dist_git_branches:
  #     - fedora-branched # rawhide updates are created automatically
  # - job: koji_build
  #   trigger: commit
  #   dist_git_branches:
  #     - fedora-all
  # - job: propose_downstream
  #   trigger: release
  #   dist_git_branches:
  #     - fedora-all
  - job: copr_build
    trigger: pull_request
    targets: &build_targets
      - centos-stream-9-aarch64
      - centos-stream-9-s390x
      - centos-stream-9-ppc64le
      - centos-stream-9-x86_64
      - centos-stream-10-aarch64
      - centos-stream-10-s390x
      - centos-stream-10-ppc64le
      - centos-stream-10-x86_64
      - fedora-all-aarch64
      - fedora-all-s390x
      - fedora-all-ppc64le
      - fedora-all
      - rhel-9-aarch64
      - rhel-9-x86_64
  - job: copr_build
    trigger: commit
    branch: main
    owner: "@osbuild"  # copr repo namespace
    project: image-builder  # copr repo name so you can consume the builds
    targets: *build_targets
